# Generated by Django 3.1.3 on 2021-01-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='equipment',
            field=models.TextField(blank=True, max_length=255, verbose_name='equipment details'),
        ),
    ]
